---
all:
  children:
    molecule:
      hosts:
        fedora44:
          ansible_connection: containers.podman.podman
          container_image: registry.fedoraproject.org/fedora:44
          container_command: sleep 1d
        fedora43:
          ansible_connection: containers.podman.podman
          container_image: registry.fedoraproject.org/fedora:43
          container_command: sleep 1d
