---
- name: Validate role inputs and platform
  ansible.builtin.import_tasks: assert.yml

- name: Manage crypto policy
  ansible.builtin.import_tasks: configure.yml
  when: enable_crypto_policy | bool
