---
# tasks file for crypto_policy

- name: Ensure package is installed
  ansible.builtin.package:
    name: "{{ crypto_policy_packages }}"
    state: present
    update_cache: yes

- name: Include Gather Aditional Facts
  ansible.builtin.include_tasks: gather_facts.yml

- name: "Current crypto-policy is {{ system_crypto_policy }}"
  ansible.builtin.debug:
    msg:
      - "Current crypto-policy is: {{ system_crypto_policy }}"
      - "Policy selected to be set on this system: {{ crypto_policy }}"
      - "Available policies: {{ system_crypto_available_policies }}"
      - "Available sub-policies: {{ system_crypto_available_subpolicies }}"

- name: Set crypto-policy from {{ system_crypto_policy }} to {{ crypto_policy | upper }}
  ansible.builtin.command: >
    update-crypto-policies
      {{ '--no-reload' if not crypto_policies_reload else '' }}
      --set {{ crypto_policy | upper }}
  register: crypto_cmd_result
  failed_when: crypto_cmd_result.rc != 0
  changed_when: system_crypto_policy != crypto_policy | upper and crypto_cmd_result.rc == 0
  when: crypto_policy is defined and system_crypto_policy != crypto_policy | upper
  notify: Reboot

- name: Check to see if FIPS mode is already set up if crypto_policy == "FIPS"
  ansible.builtin.command: /usr/sbin/fips-mode-setup --is-enabled
  register: fips_mode
  when: crypto_policy is defined and crypto_policy | upper == "FIPS"
  failed_when: false
  changed_when: false

- name: Enabling FIPS mode if crypt_policy set to FIPS
  ansible.builtin.command: /usr/bin/fips-mode-setup --enable
  when: ( crypto_policy is defined and crypto_policy | upper == "FIPS") and fips_mode.rc == "2"

- name: Include Gather Aditional Facts
  ansible.builtin.include_tasks: gather_facts.yml
